level_0 = {
    'terrain':'../levels/0/first_level_terrrain.csv',
    'coins':'../levels/0/first_level_coins.csv',
    'fg palms':'../levels/0/first_level_fg_palms.csv',
    'bg palms':'../levels/0/first_level_bg_palms.csv',
    'crates':'../levels/0/first_level_crates.csv',
    'enemies':'../levels/0/first_level_enemies.csv',
    'constraints':'../levels/0/first_level_constrains.csv',
    'player':'../levels/0/first_level_player.csv',
    'grass':'../levels/0/first_level_grass.csv',
	'node_pos': (110,400),
	'unlock': 1,
	'node_graphics': '../graphics/overworld/0'}
level_1 = {
    'terrain':'../levels/0/first_level_terrrain.csv',
    'coins':'../levels/0/first_level_coins.csv',
    'fg palms':'../levels/0/first_level_fg_palms.csv',
    'bg palms':'../levels/0/first_level_bg_palms.csv',
    'crates':'../levels/0/first_level_crates.csv',
    'enemies':'../levels/0/first_level_enemies.csv',
    'constraints':'../levels/0/first_level_constrains.csv',
    'player':'../levels/0/first_level_player.csv',
    'grass':'../levels/0/first_level_grass.csv',
    'node_pos': (300,220),
    'unlock': 2,
    'node_graphics': '../graphics/overworld/1'}
level_2 = {
    'terrain':'../levels/0/first_level_terrrain.csv',
    'coins':'../levels/0/first_level_coins.csv',
    'fg palms':'../levels/0/first_level_fg_palms.csv',
    'bg palms':'../levels/0/first_level_bg_palms.csv',
    'crates':'../levels/0/first_level_crates.csv',
    'enemies':'../levels/0/first_level_enemies.csv',
    'constraints':'../levels/0/first_level_constrains.csv',
    'player':'../levels/0/first_level_player.csv',
    'grass':'../levels/0/first_level_grass.csv',
    'node_pos': (480,610),
    'unlock': 3,
    'node_graphics': '../graphics/overworld/2'}
level_3 = {
    'terrain':'../levels/0/first_level_terrrain.csv',
    'coins':'../levels/0/first_level_coins.csv',
    'fg palms':'../levels/0/first_level_fg_palms.csv',
    'bg palms':'../levels/0/first_level_bg_palms.csv',
    'crates':'../levels/0/first_level_crates.csv',
    'enemies':'../levels/0/first_level_enemies.csv',
    'constraints':'../levels/0/first_level_constrains.csv',
    'player':'../levels/0/first_level_player.csv',
    'grass':'../levels/0/first_level_grass.csv',
    'node_pos': (610,350),
    'unlock': 4,
    'node_graphics': '../graphics/overworld/3'}
level_4 = {
    'terrain':'../levels/0/first_level_terrrain.csv',
    'coins':'../levels/0/first_level_coins.csv',
    'fg palms':'../levels/0/first_level_fg_palms.csv',
    'bg palms':'../levels/0/first_level_bg_palms.csv',
    'crates':'../levels/0/first_level_crates.csv',
    'enemies':'../levels/0/first_level_enemies.csv',
    'constraints':'../levels/0/first_level_constrains.csv',
    'player':'../levels/0/first_level_player.csv',
    'grass':'../levels/0/first_level_grass.csv',
    'node_pos': (880,210),
    'unlock': 5,
    'node_graphics': '../graphics/overworld/4'}
level_5 = {
    'terrain':'../levels/0/first_level_terrrain.csv',
    'coins':'../levels/0/first_level_coins.csv',
    'fg palms':'../levels/0/first_level_fg_palms.csv',
    'bg palms':'../levels/0/first_level_bg_palms.csv',
    'crates':'../levels/0/first_level_crates.csv',
    'enemies':'../levels/0/first_level_enemies.csv',
    'constraints':'../levels/0/first_level_constrains.csv',
    'player':'../levels/0/first_level_player.csv',
    'grass':'../levels/0/first_level_grass.csv',
    'node_pos': (1050,400),
    'unlock': 5,
    'node_graphics':'../graphics/overworld/5'}

levels = {
	0: level_0,
	1: level_1,
	2: level_2,
	3: level_3,
	4: level_4,
	5: level_5}